## Import libraries and raw data

In [5]:
#importing one month's worth of raw data
import pandas as pd
df = pd.read_csv('CMV_July_2022.csv')

## Organize data into comment tree index

In [7]:
#Tentative code for organizing into comment trees


#Create a dictionary mapping from each entry's ID to its parent ID and link ID
id_to_parent_and_link = df.set_index('id')[['parent_id', 'link_id']].to_dict('index')

# Function to find the top-level post of an entry
def find_top_level_post(entry_id):
    # If the top-level post of the entry is already in the mapping, return it
    if entry_id in entry_to_top_level:
        return entry_to_top_level[entry_id]

    # If the entry does not exist or its parent_id is the same as its link_id, it is a top-level post
    if entry_id not in id_to_parent_and_link or id_to_parent_and_link[entry_id]['parent_id'] == id_to_parent_and_link[entry_id]['link_id']:
        top_level_post_id = entry_id
    else:
        # If not, find the top-level post of the parent
        top_level_post_id = find_top_level_post(id_to_parent_and_link[entry_id]['parent_id'])

    # Add the top-level post of the entry to the mapping
    entry_to_top_level[entry_id] = top_level_post_id

    return top_level_post_id

# Initialize an empty dictionary to store the mapping from each entry to its top-level post
entry_to_top_level = {}

# Find the top-level post of each entry and add it to the mapping
for entry_id in id_to_parent_and_link:
    find_top_level_post(entry_id)

# Initialize an empty dictionary to store the mapping from top-level posts to all their descendants
top_level_to_all_descendants = {}

# Add each entry to the list of descendants of its top-level post
for entry_id, top_level_post_id in entry_to_top_level.items():
    if top_level_post_id not in top_level_to_all_descendants:
        top_level_to_all_descendants[top_level_post_id] = []
    top_level_to_all_descendants[top_level_post_id].append(entry_id)

# For simplicity and readability, let's just display the first 5 items from the dictionary
first_5_top_level_to_all_descendants_items = list(top_level_to_all_descendants.items())[:5]

first_5_top_level_to_all_descendants_items

[('iegb6f2', ['iegb6f2']),
 ('iegb894', ['iegb894']),
 ('iegbbaw', ['iegbbaw']),
 ('t1_ieg573y', ['t1_ieg573y', 'iegbelu']),
 ('iegbhth', ['iegbhth'])]

## Filter to only keep comment trees where OP responded

## Remove comment trees where top-level post is less than 50 words

In [6]:
#link_id is the original post, so if that's the parent_id, it's a top level comment
top_level_comments = df[df['parent_id'] == df['link_id']]
top_level_comments

#code to remove top level comments with less than 50 words
tlc_50words = top_level_comments[top_level_comments['body'].str.split().str.len() >= 50]
# Display the entries
tlc_50words

,Unnamed: 0,id,link_id,parent_id,CreatedAt,author,ups,downs,score,edited,...,subreddit_type,subreddit_id,stickied,is_submitter,body,error,subreddit,Month,Year,Day
4,4,iegbhth,t3_vp0wc8,t3_vp0wc8,2022-07-01 07:02:34,MercurianAspirations,NaN,NaN,17,True,...,public,t5_2w2s8,False,False,It exists in places where the public transport...,NaN,changemyview,7,2022,1
19,19,iegcjl9,t3_volzg1,t3_volzg1,2022-07-01 07:10:14,Net-Troll,NaN,NaN,2,False,...,public,t5_2w2s8,False,False,"Eat when your body tells you to eat, not on so...",NaN,changemyview,7,2022,1
26,26,iegcv7c,t3_voytbc,t3_voytbc,2022-07-01 07:12:36,draculabakula,NaN,NaN,1,False,...,public,t5_2w2s8,False,False,The work is optional mentality has already suc...,NaN,changemyview,7,2022,1
39,39,iegdsrh,t3_vouzwo,t3_vouzwo,2022-07-01 07:19:18,Kerostasis,NaN,NaN,3,False,...,public,t5_2w2s8,False,False,&gt;We all grew up envying supercars and the g...,NaN,changemyview,7,2022,1
43,43,iege0js,t3_voroqg,t3_voroqg,2022-07-01 07:20:50,Tanaka917,NaN,NaN,1,False,...,public,t5_2w2s8,True,False,Your post has been removed for breaking Rule E...,NaN,changemyview,7,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149249,149249,iig04wu,t3_wd0uq7,t3_wd0uq7,2022-07-31 16:40:28,English-OAP,NaN,NaN,1,False,...,public,t5_2w2s8,False,False,I don't believe a machine can come up with a n...,NaN,changemyview,7,2022,31
149261,149261,iig0fqg,t3_wc7pu1,t3_wc7pu1,2022-07-31 16:42:52,miragesarereal,NaN,NaN,1,False,...,public,t5_2w2s8,False,False,"Idk your gender but for me saying not all men,...",NaN,changemyview,7,2022,31
149269,149269,iig0mqh,t3_wd0uq7,t3_wd0uq7,2022-07-31 16:44:25,BlowjobPete,NaN,NaN,1,True,...,public,t5_2w2s8,False,False,"We still place great importance on hand-made, ...",NaN,changemyview,7,2022,31
149278,149278,iig0vmb,t3_wczne2,t3_wczne2,2022-07-31 16:46:25,tyzzex,NaN,NaN,1,True,...,public,t5_2w2s8,False,False,There are spots at beaches that aren't so crow...,NaN,changemyview,7,2022,31
149311,149311,iig1iww,t3_wd25iq,t3_wd25iq,2022-07-31 16:51:36,ModaGamer,NaN,NaN,12,False,...,public,t5_2w2s8,False,False,I guess the main critique of your argument is ...,NaN,changemyview,7,2022,31